version: '3.5'
services:
  neo4j:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - ./db/dbms:/data/dbms

  neo4jtest:
    image: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - "7475:7474"
      - "7688:7687"
    volumes:
      - ./dbtest/dbms:/data/dbms

  dnetwork:
    image: dnetwork:latest
    environment:
      API_SERVER_HOST: dnetwork
      NEO4J_URL: "bolt://neo4j:7687"
      NEO4J_TEST_URL: "bolt://neo4jtest:7687"
      NEO4J_USERNAME: "neo4j"
      NEO4J_PASSWORD: "password"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
